const getJobWlDailyCounting = `
select
 description ,count(*) total_account from
custom.payroll
where
 description in (
      'PAYROLL - TIDAK LOLOS AV, AV MINUS > 1 TITIK DALAM 1 BULAN PADA BULAN-3 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', 
      'PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', 
      'PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA PADA BULAN-1 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', --add 1
      'PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA PADA BULAN-2 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', --add 1
      'PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA PADA BULAN-3 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', --add 1
      'PAYROLL - TIDAK LOLOS AV, AV MINUS > 1 TITIK DALAM 1 BULAN PADA BULAN-1 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK',
      'PAYROLL - TIDAK LOLOS AV, AV MINUS > 1 TITIK DALAM 1 BULAN PADA BULAN-2 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK',
      'PAYROLL - TIDAK LOLOS MAX KOLEK',
      'TIDAK LOLOS MAX KOLEK',
      'PAYROLL - TIDAK LOLOS, WORK END DATE TIDAK VALID',
      'PAYROLL - TIDAK LOLOS, WORK END DATE < TODAY',
      'PAYROLL - WORK END DATE TIDAK VALID',
      'PAYROLL - WORK END DATE < TODAY')
    and pendapatan_netto_wl > 0
    and bank_code = '002'
    -- and tgl_gajian_wl != '1901-01-01'
    and del_flag = 'true' group by description
  union
  select
 description ,count(*) total_account from
custom.payroll
where
   description in (
    'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV MINUS > 1 TITIK DALAM 1 BULAN PADA BULAN-3 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', 
    'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', 
    'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA PADA BULAN-1 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', --add 1
    'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA PADA BULAN-2 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', --add 1
    'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA PADA BULAN-3 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', --add 1
    'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV MINUS > 1 TITIK DALAM 1 BULAN PADA BULAN-1 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', 
    'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV MINUS > 1 TITIK DALAM 1 BULAN PADA BULAN-2 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK',
    'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS MAX KOLEK',
    'B.497/DPD/PMN/08/2024 - TIDAK LOLOS MAX KOLEK',
    'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS, WORK END DATE TIDAK VALID',
    'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS, WORK END DATE < TODAY',
    'B.497/DPD/PMN/08/2024 - PAYROLL - WORK END DATE TIDAK VALID',
    'B.497/DPD/PMN/08/2024 - PAYROLL - WORK END DATE < TODAY'
      )
    and pendapatan_netto_wl > 0 
    and bank_code = '002'
    and del_flag = 'true' -- ubah statusnya false kalo mau cek yang existing / after lu hit update querynya
    group by description;`

module.exports = { getJobWlDailyCounting }