const UpdateJobWlDaily = ()=>{
    return `
update custom.payroll
 	set del_flag ='false'
where payroll.acctno_wl in (
    select acctno_wl from custom.payroll where
    description in (
        'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV MINUS > 1 TITIK DALAM 1 BULAN PADA BULAN-3 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', 
        'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', 
        'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA PADA BULAN-1 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', --add 1
        'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA PADA BULAN-2 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', --add 1
        'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV < -10 JUTA PADA BULAN-3 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', --add 1
        'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV MINUS > 1 TITIK DALAM 1 BULAN PADA BULAN-1 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK', 
        'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS AV, AV MINUS > 1 TITIK DALAM 1 BULAN PADA BULAN-2 ; LOLOS MINIMAL CREDIT ; LOLOS BPJS/DPLK',
        'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS MAX KOLEK',
        'B.497/DPD/PMN/08/2024 - TIDAK LOLOS MAX KOLEK',
        'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS, WORK END DATE TIDAK VALID',
        'B.497/DPD/PMN/08/2024 - PAYROLL - TIDAK LOLOS, WORK END DATE < TODAY',
        'B.497/DPD/PMN/08/2024 - PAYROLL - WORK END DATE TIDAK VALID',
        'B.497/DPD/PMN/08/2024 - PAYROLL - WORK END DATE < TODAY')
        and pendapatan_netto_wl > 0
        and bank_code = '002'
        -- and tgl_gajian_wl != '1901-01-01'
        and del_flag = 'true'
    );`
}

module.exports = { UpdateJobWlDaily }